#!/usr/bin/perl
# Announce the next Every Other Friday, aka EOF
# For use for K-State LUG

use strict;
use Hackabot::Client;
use Time::Local;

my $hbc = Hackabot::Client->new;
my $msg = $hbc->readline;
my $nick = $hbc->sent_by;
my $chan = $hbc->channel;

my $now = time;
my $ref = timelocal(0,0,17,14,11,2007);

my $is_dst = (localtime($now))[8];

my $dif = (1209600-($is_dst?3600:0))-($now-$ref)%1209600;

my $days = int($dif/86400);
my $hours = int(($dif-$days*86400)/3600);
my $minutes = int(($dif-$days*86400-$hours*3600)/60);
my $seconds = $dif%60;

if ($dif+7200>1209600)
{
        print "send Woot! It is EOF!\n";
} else {
        printf "send There are %d days, %d hours, %d minutes and %d seconds to the next Every Other Friday.\n",$days,$hours,$minutes,$seconds;
}

